- limacharlie/Net.py
Adding new parameters supported by lc-net to customize the wireguard configs generated during provisioning.
> New params to customize WG config.

- limacharlie/Sensor.py
Adding API call to list all children events of a given atom.
> Adding call to fetch children events.

- limacharlie/SpotCheck.py
- limacharlie/__init__.py
- limacharlie/__main__.py
- setup.py
Making the SpotCheck feature accessible via `limacharlie spotcheck --help`.
Was only accessible via `python -m limacharlie.SpotCheck` before.
> Support SpotCheck via "limacharlie spotcheck"

- limacharlie/Comms.py
Add call to post a message to a room
> Add call to post a message to a room

- limacharlie/Manager.py
Supporting the new Groups API.
> Adding Groups API.

- limacharlie/Replicants.py
- limacharlie/Sync.py
Days retention is currently ignored from the config
> Pass days retention when adding an artifact rule

- limacharlie/Configs.py
- limacharlie/Manager.py
- tests/test_sync.py
Add support for OrgConfigs (called OrgValues in the Go SDK) and Sync support for those too.
> Add orgConfig Setter.

- limacharlie/Manager.py
- limacharlie/__init__.py
- setup.py
Adding new accessor to get all tags.
> Get all tags

- limacharlie/Replay.py
- limacharlie/__init__.py
- setup.py
Bug in transmitting literal events.
> Fix events to replay.

- limacharlie/Manager.py
Adding new accessor to configure USP.
> Accessor for configuring USP.

- limacharlie/__init__.py
- setup.py
> Version bump

- limacharlie/Firehose.py
- limacharlie/Logs.py
- limacharlie/Manager.py
- limacharlie/Replay.py
- limacharlie/Search.py
- limacharlie/Sensor.py
- limacharlie/SpotCheck.py
- limacharlie/Spout.py
- limacharlie/__init__.py
- limacharlie/utils.py
- requirements.txt
- samples/demo_firehose.py
- samples/demo_spout.py
- setup.py
Remove gevent and use native packages
> Remove gevent from code base

- limacharlie/Hive.py
- limacharlie/__main__.py
> Hive support

- limacharlie/Manager.py
Expose the new template at creation capability.
> Support passing template to org creation.

- limacharlie/Manager.py
- limacharlie/__main__.py
Adding accessor for new Schema API and CLI.
> Adding schema API and CLI.

- limacharlie/Manager.py
- limacharlie/Spout.py
- limacharlie/__main__.py
Fixing issues with Spout since we moved away from gevent. Also made Spouts available via the CLI.
> Fix Spout with Threading and add CLI.

- tests/test_core.py
> fixing failed test in test_core
- [ x] Bug fix (non-breaking change that fixes an issue)
> Fix [#1]()
> fix failing test in test_core

- limacharlie/Firehose.py
- limacharlie/Manager.py
- setup.py
- tests/test_sync.py
A few small fixes and new API implementations.
> More threading fixes

- limacharlie/Manager.py
Add endpoint to upgrade sensor versions.
> Add an accessor to set the sensor versions.

- limacharlie/Configs.py
Support glob patterns in include files.
> Add support for globbing in Configs includes.

- limacharlie/Configs.py
Disable globbing include until we can add proper tests.
> Temporarily disable glob includes.

- limacharlie/Configs.py
Infra as code now supports file globbing.
> Enable file globbing in infra as code.

- limacharlie/SpotCheck.py
- limacharlie/__init__.py
- limacharlie/utils.py
- setup.py
Fixing timing and parallel bugs.
> Some parallel and timing fixes.

- limacharlie/Manager.py
- limacharlie/__init__.py
- setup.py
Support for new sensor selector expressions.
> Add support for new sensor selector expression.

- limacharlie/Sensor.py
- limacharlie/__main__.py
Adding support for sending historical events to an Output.
> Add support for sending events to an output.

- limacharlie/Replay.py
- limacharlie/__init__.py
- setup.py
Replay now supports specifying a rule namespace.
> Add namespace support for Replay.

- limacharlie/Hive.py
Add ability for user code to short circuit the Update Hive call.
> Enable short circuit in hive Update.

- limacharlie/Manager.py
Adding new APIs for working with installation keys.
> Adding new APIs.

- limacharlie/__init__.py
- setup.py
> Increase version for release of configs push tweak.

- limacharlie/Sensor.py
- limacharlie/__init__.py
- setup.py
> Support multi-tag.

- limacharlie/Hive.py
> fixes issues when attempting to load None data when creating HiveRecord
- [ x] Bug fix (non-breaking change that fixes an issue)
> Fix [#1]()
> Fix attempt of json load on none data for HiveRecord

- limacharlie/Configs.py
- limacharlie/__init__.py
- setup.py
Missed a spot to disable automatic backoff from infra service.
> Conf tweaks

- limacharlie/Hive.py
- limacharlie/__init__.py
- setup.py
Fix how we quote the keys for hive.
> Fix quoting for rules.

- limacharlie/Sensor.py
New endpoint to count retained events for a sensor.
> Accessor for new event count API.

- limacharlie/Replay.py
- limacharlie/__init__.py
- setup.py
Support Replay dry-run requests.
> Replay dryrun

- limacharlie/Manager.py
- limacharlie/__init__.py
- limacharlie/__main__.py
- setup.py
Add a new call to get basic org stats and a CLI to accompany it: `limacharlie org_stats`
> Add a convenient CLI to get org stats.

- limacharlie/__init__.py
- setup.py
> Bump up release version.

- limacharlie/Configs.py
- limacharlie/Query.py
- limacharlie/Replicants.py
Support for Hives, installation keys and yara in infra-as-code.
Add Yara Source access.
Document new aggregation in lcql.
> Var updates

- limacharlie/Configs.py
- limacharlie/__init__.py
- setup.py
> Remove Net in infra as code.

- limacharlie/Configs.py
- limacharlie/Manager.py
- limacharlie/Query.py
- limacharlie/Replay.py
- limacharlie/__init__.py
- limacharlie/utils.py
- setup.py
Huge overhaul of the LCQL CLI interface including auto-completion.
Also paginated queries whenever possible.
> Query tweaks

- limacharlie/Query.py
- limacharlie/Replay.py
Typo from command name change.
Fix smaller bugs.
> Command is "n", not "next" anymore.

- limacharlie/Query.py
- limacharlie/__init__.py
- setup.py
Add dryrun capability to lcql.
> Enable autocomplete in dryrun.

- limacharlie/Manager.py
- limacharlie/__init__.py
- setup.py
- Access to editing installation keys.
- Access to setting quotas.
> Edit Installation Keys and support Installation Key Quotas.

- limacharlie/Manager.py
- limacharlie/__init__.py
- setup.py
Making list all online API call accessible in SDK.
> Add Accessor for all online sensors.

- limacharlie/Hive.py
- limacharlie/__init__.py
- setup.py
Support supplying the data for a hive record through stdin to make it easier to show simple one-liners.
> Support hive data on stdin.

- limacharlie/Manager.py
Adding an accessor to the existing API call.
> Add call to get detection by ID.

- limacharlie/__init__.py
- limacharlie/__main__.py
- setup.py
mass-tag feature to tag lots of endpoints with one command/
> Adding a mass-tag CLI command to tags multiple sensors.

- limacharlie/__main__.py
Fixed typo in help text.
N/A
N/A
> Fixed typo

- limacharlie/Manager.py
- limacharlie/Search.py
IOC search on website allows for searching for IOCs by `package_name`--making this match.
> Adding `package-name` to IOC search

- limacharlie/__init__.py
- setup.py
> Bump up version.

- limacharlie/Query.py
- limacharlie/Replay.py
- limacharlie/__init__.py
- setup.py
Add support for stream selection for replay.
> Replay audit detect

- limacharlie/Extensions.py
- limacharlie/__init__.py
- setup.py
Adding an env switch to make it easier to change extensions across multiple environments.
> Adding an env switch to extensions.

- limacharlie/Extensions.py
Fixing the calls to create and update extensions.
> Fix the extension creation and update.

- limacharlie/Hive.py
Fix the space encoding used for Hive records.
> Fix the space encoding in hive.

- README.md
- limacharlie/Manager.py
- limacharlie/__main__.py
Add a CLI option to list sensors matching a selector.
> Add a CLI to list sensors.

- limacharlie/Manager.py
- limacharlie/__init__.py
- limacharlie/__main__.py
- setup.py
Exposing existing functionality through CLI.
> Expose search by IP and search by hostname prefix in CLI.

- limacharlie/Spout.py
- limacharlie/__init__.py
- setup.py
Fix hanging of non daemon threads.
> Fix hanging thread

- limacharlie/Configs.py
- limacharlie/__init__.py
- setup.py
Manage the Yara Hive through infra as code.
> Enable the Yara hive.

- limacharlie/Hive.py
- limacharlie/__init__.py
- setup.py
Convenience wrapper for Hives that expect a raw value in a single key like:
```
limacharlie hive set yara --key my-rule --data rule.yara --data-key rule
```
> Add a convenience wrapper for Hive.

- limacharlie/Extensions.py
The signature of the extension creation endpoint changed a bit.
> Extension definition endpoint changed a bit.

- Dockerfile
- cloudbuild.yaml
- cloudbuild_pr.yaml
Add the auto-build of the CLI container and publishing.
> Produce container

- cloudbuild.yaml
- cloudbuild_pr.yaml
- limacharlie/Billing.py
- limacharlie/Configs.py
- limacharlie/Extensions.py
- limacharlie/Manager.py
- limacharlie/__init__.py
- requirements.txt
- setup.py
- Adding some billing accessors.
- Adding extension re-key accessor.
- Infra as Code now validates that all non-wildcard files are imported properly and errors otherwise.
- Adding transform testing accessor.
- Adding runtime metadata accessor.
> New quality of life.

- limacharlie/Configs.py
> Missing hives in sync.

- limacharlie/Configs.py
- limacharlie/__init__.py
- setup.py
Fix bug with include logic of infra as code.
> Fix include bug

- limacharlie/Configs.py
Fixing merge in includes of infra as code for hives.
> Fixing include case with hives.

- limacharlie/__init__.py
- setup.py
> Forgot to bump version in file.

- limacharlie/Billing.py
- limacharlie/Spout.py
Adding a few billing accessors.
Fixing an issue with the Spouts.
> Spout fixes

- limacharlie/Manager.py
- limacharlie/WebhookSender.py
> Adding WebHook sender class and methods to python
> Fix [#1]()
> Adding WebHook sender class and methods to python

- limacharlie/__init__.py
- setup.py
> Version 4.7.0 contains WebhookSender functionality 
> Fix [#1]()
> Version update 4.7.0

- limacharlie/__init__.py
- setup.py
> Description here
> Fix [#1]()
> adding webook sender to init file and update version

- limacharlie/Sensor.py
> Add accessor for sealing.

- README.md
- limacharlie/Extensions.py
- fixes incorrect 'default=None' on dry-run arg
- adds Extensions helper to README'
- fix on cli returning 'null' for all commands
> Hotfix convert rules args parser

- limacharlie/Hive.py
Add the new hive comment support.
> Add the new hive comment support.

- limacharlie/__main__.py
> Small fixes

- limacharlie/Spout.py
> New billing stream

- limacharlie/Billing.py
New accessor for User Auth Parameters.
> Add accessor for user auth requirements.

- limacharlie/Billing.py
- limacharlie/__init__.py
- setup.py
Adding support for a custom format for invoices.
> Add format support for invoices.

- requirements.txt
- setup.py
Remove ARL from dependencies always installed so that we can provide a pure-python implementation.
> Remove ARL from dependencies.

- limacharlie/Model.py
- limacharlie/__main__.py
> Data models cli
> Fix [#1]()
> Data models cli

- limacharlie/Hive.py
> Added functionality to hive for re-name
> Fix [#1]()
> hive rename cli addition

- limacharlie/Manager.py
> Accessor for org name availability.

- limacharlie/Hive.py
- limacharlie/Model.py
> Add model table view option, fix validation check in hive rename
> Fix [#1]()
> Model table view

- limacharlie/UserPreferences.py
- limacharlie/__init__.py
- setup.py
Object to interact with the new User Preference service.
> Draft code to modify and get user preferences.

- limacharlie/Hive.py
- limacharlie/Model.py
- limacharlie/__init__.py
- setup.py
Add accessor and CLI for listing entries from model.
> Model list

- limacharlie/Model.py
- setup.py
> Remove model hop param from model query request and update example comments
Fix refractionPOINT/tracking#1
> Remove model hop param

- limacharlie/Extensions.py
Use the compressed extension request by default to avoid configs too large.
> Ext req compression

- limacharlie/__init__.py
- setup.py
> Bump version

- limacharlie/Manager.py
- limacharlie/__init__.py
- limacharlie/__main__.py
- setup.py
Function and CLI access to the MITRE report: `limacharlie mitre-report`.
> Add accessor for mitre report.

- limacharlie/__init__.py
- limacharlie/__main__.py
- setup.py
MITRE JSON format was not proper JSON.
> Fix JSON output

- limacharlie/Manager.py
- limacharlie/__main__.py
- limacharlie/versions.py
New mass-upgrade tool in the CLI.
> Draft of a mass upgrade.

- limacharlie/Manager.py
- limacharlie/Model.py
- limacharlie/__init__.py
- setup.py
Tweaks to Models access.
Adding new function to invite users.
> Model tweaks

- setup.py
This bumps version in setup.py (something I forgot to do in #155).
> chore: Bump version in setup.py

- limacharlie/Configs.py
- limacharlie/__init__.py
- setup.py
> Add playbook hive support.

- limacharlie/__init__.py
- setup.py
Re-releasing previous version, a hard coded API gateway was left in there.
> Bump version, previous had an API gateway hardcoded.

- cloudbuild_pr.yaml
- limacharlie/Manager.py
- limacharlie/__init__.py
- setup.py
- tests/integration/test_core.py
Add:
- getOrgInfo
- add allowed_ip_range to addApiKey
- add annotations
Remove the reruns of integration tests as it masked the underlying error, took me a while to figure it out.
> Api key ip

- limacharlie/Replay.py
- limacharlie/__init__.py
- setup.py
Just adding support for the iterator pattern on the query interface to simplify cases where a user wants to make a quick query and get results without caring about stats.
> Query iter

- limacharlie/Replay.py
- limacharlie/__init__.py
- setup.py
Add support for a flag that already is supported by the service.
> Replay validate
