refractionPOINT/python-limacharlie

limacharlie/Configs.py
limacharlie/Manager.py

Adding Net Policies to the configs managed by the Configs CLI tool.
Also adding a `--all` convenience function to fetch/push all configs.
Also adding a warning and failure when no type of config is actually requested.

Net pol configs

---

limacharlie/SpotCheck.py
limacharlie/__init__.py
setup.py

Python3 strings do not support `.decode('hex')`. Moving to a quick and dirty check for both.

Support hash check in SpotCheck Python3.

---

limacharlie/Manager.py

Adding support for the endpoint that lists all the orgs that a user api key has access to.

Add an endpoint to list orgs api key has access to.

---

limacharlie/Manager.py

Listing orgs from a user key could fail with a 431 because the JWT from LC was too big. This JWT is not actually required for this call, so we add the flag to not attach it to the request.

Fix listing of orgs from user key.

---

limacharlie/Manager.py
limacharlie/Search.py

Adding `service_name` to list of indicator types--was previously listed in the help but not actually usable when running `limacharlie search -t "service_name" ...`.

Adding `service_name` to list of indicator types

---

limacharlie/Search.py

Adding the `uid`, if it's available, to the manager configuration in order to allow the use of user API keys. Otherwise, when using a uid in the `~/.limacharlie` file, it doesn't get picked up when trying to run IOC searches across multiple environments using a user API key.

adding the uid, if it's available, to the manager configuration in order to allow the use of user API keys

---

limacharlie/Sensor.py

The `sensor.tag` function required you to provide a TTL, even if you didn't want/need one to be applied. Set the default to `None` in the event that there was no need for a TTL to be set and an error is no longer returned when simply sending `sensor.tag("tag")`.

Remove requirement for TTL when adding a tag to a sensor

---

limacharlie/Configs.py

Move the config syncing to use one or the other only, not local and cloud service at the same time. It only muddies the water when an error occurs.

Use service-only for config pushes by default.

---

limacharlie/Configs.py

`glob.iglob( include )` recursive defaults to `False`, added `glob.iglob( include, recursive=True )` so `**` calls recursively. 
Example, for pushing rules in nested directories:
```
version: 3
include:
- rules/**/*.yml
```

Allow directory to glob recursively

---

limacharlie/Configs.py

The Golang YAML libs support yaml v1.1, not 1.2, so make the infra as code in python output in 1.1.

Specify yaml v1.1 for infra as code for Go compat.

---

limacharlie/Manager.py

Enable installation keys using root CA.

Add support for making installation key use public root ca.

---

limacharlie/Extensions.py

New cli command and logic added that converts an org's `dr-general` and `dr-managed` rules using old service request calls into new extension requests
Syntax checks for rules verified in [notion doc](https://www.notion.so/Svc-ext-rules-8b1e189b43bc4a01b821d84b862d29aa)
Rules impacted:
- dumper
- pager-duty
- reliable-tasking
- velociraptor
- yara
- zeek
📷 Sample of cli response from Dry Run of command:

Convert rules svc to ext

---

limacharlie/Extensions.py

Quick fix. Noticed there was an incorrect args reference. Was affecting cli command syntax when I was playing with it.

fix incorrect args reference

---

limacharlie/Extensions.py

Improvements ahead of release to cli:
- noticed `make_transform_exp` was not working as expected on references. Fixed with added specificity
- using new `argparse.BooleanOptionalAction` to enhance `--dry-run` flag use (`--no-dry-run` to turn off)
- Yara sources are a [ ] str not a str needing transform exp. Fixed.
- better ux on cli returns 
Documentation pages drafted for cli syntax sitting ready to go (specifies `--dry-run` and `--no-dry-run` details). Will publish on release

Fixes for convert rules args parser

---

limacharlie/Manager.py

Mark FP and Rules endpoints as deprecated to encourage the move to Hive.

Mark FP and Rules accessors as deprecated.

---

CHANGELOG.md
Dockerfile
README.md
cloudbuild.yaml
cloudbuild_pr.yaml
limacharlie/__init__.py
requirements-tests.txt
setup.py

This pull request should fix the Cloud Build workflow which runs on `master` branch and builds + publishes Docker Image to Docker Hub.
* Re-try flaky tests on failures (common issue with integration tests)
* Test build + verify .tar.gz source distribution
* Version Docker images - in addition to `latest` also publish tag which corresponds to the tool version
Fix refractionPOINT/tracking#3051

fix [refractionPOINT/tracking#3025] Fix Docker image build + push workflow

---

limacharlie/Hive.py

Adding simple flag to output only the record data and not the whole record. This makes quick "edit this and push it back" simpler as it avoids the user needing to remove the record envelope from the data returned.

Add flag to print only data, useful for quick edits.

---

limacharlie/term_utils.py

This pull request includes a couple of small improvements in the `limacharlie query --labs` command output:
- Limit maximum number of facet field and facet field values we print.
- Limit histogram bar height.
- Limit tjhe total number of histogram entries we display to avoid it from wrapping across multiple lines.
Example output with those changes in place:
- #167
Part of refractionPOINT/tracking#3132

Small improvements in the limacharlie query command

---

limacharlie/Manager.py

Adding a stderr warning when we received a header from the API indicating that the request was over-quota (since we don't currently enforce).

Emit stderr warning on over-quota.

---

limacharlie/Manager.py

When using a JWT-only SDK, if we get an auth error, there is no way for us to refresh the JWT since we don't have an API key, so we will never get ourselves out of the auth error. So instead of reporting an error down the line about missing an API key, return the original auth error here.

Handle jwt-only auth errors better.
